# Generated by Django 4.2.13 on 2024-05-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studijeuxolympiques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user_admin',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='token_ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='studijeuxolympiques.tokenticket'),
        ),
    ]
