# Generated by Django 4.2.13 on 2024-05-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studijeuxolympiques', '0003_epreuvesportive_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
