# Generated by Django 4.2.13 on 2024-05-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studijeuxolympiques', '0004_achat_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenuser',
            name='association_token',
        ),
        migrations.RemoveField(
            model_name='tokenuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='token_ticket',
        ),
        migrations.DeleteModel(
            name='AssociationToken',
        ),
        migrations.DeleteModel(
            name='TokenTicket',
        ),
        migrations.DeleteModel(
            name='TokenUser',
        ),
    ]
