# Generated by Django 4.2.13 on 2024-05-24 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studijeuxolympiques', '0005_remove_tokenuser_association_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achat',
        ),
    ]
